#define LED_ESC     0
#define LED_F1      1
#define LED_F2      2
#define LED_F3      3
#define LED_F4      4
#define LED_F5      5
#define LED_F6      6
#define LED_F7      7
#define LED_F8      8
#define LED_F9      9
#define LED_F10     10
#define LED_F11     11
#define LED_F12     12
#define LED_PSCR    13
#define LED_SCLK    14
#define LED_PAUS    15
#define LED_GRV     16
#define LED_1       17
#define LED_2       18
#define LED_3       19
#define LED_4       20
#define LED_5       21
#define LED_6       22
#define LED_7       23
#define LED_8       24
#define LED_9       25
#define LED_0       26
#define LED_MINS    27
#define LED_EQL     28
#define LED_BSPC    29
#define LED_INS     30
#define LED_HOME    31
#define LED_PGUP    32
#define LED_TAB     33
#define LED_Q       34
#define LED_W       35
#define LED_E       36
#define LED_R       37
#define LED_T       38
#define LED_Y       39
#define LED_U       40
#define LED_I       41
#define LED_O       42
#define LED_P       43
#define LED_LBRC    44
#define LED_RBRC    45
#define LED_BSLS    46
#define LED_DEL     47
#define LED_END     48
#define LED_PGDN    49
#define LED_CAPS    50
#define LED_A       51
#define LED_S       52
#define LED_D       53
#define LED_F       54
#define LED_G       55
#define LED_H       56
#define LED_J       57
#define LED_K       58
#define LED_L       59
#define LED_SCLN    60
#define LED_QUOT    61
#define LED_ENT     62
#define LED_LSFT    63
#define LED_Z       64
#define LED_X       65
#define LED_C       66
#define LED_V       67
#define LED_B       68
#define LED_N       69
#define LED_M       70
#define LED_COMM    71
#define LED_DOT     72
#define LED_SLSH    73
#define LED_RSFT    74
#define LED_UP      75
#define LED_LCTL    76
#define LED_LGUI    77
#define LED_LATL    78
#define LED_SPC     79
#define LED_RALT    80
#define LED_FN      81
#define LED_APP     82
#define LED_RCTL    83
#define LED_LEFT    84
#define LED_DOWN    85
#define LED_RGHT    86
